dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "ar28d0YsJGXPU8QmSQ3GDqgDlrlWTEpgc3FjjZ4kSbC9FvUQ85wgUfrRcdiGNGsyQaiaGmDfz6Bd/BGwyPR7CrM7iNBuQ9PU4h/zrXN5fIBiqrHJT4j410brKcSMarLn5nnWvHPMn/+qjNG6B6RUo/enPsUE3D/G/iKpRv8u47HQHwTKiEhaisYkMwzHoUS7lzaekJL2AUJYdIB9qgXPRpZJwQQzQNkNYcNGiCDbCil2X4tmh2XDmH+hiVKPnyU3dVPLgh0jyLqxl1j8++2ti7iT8aSJwnnsHk/SS2WLf2IEhKTU7O3/a8AN2kXVmtJCgMj9Hhnx0IiCrIfF758pxRyB/zOAxzO6mCE78psQOd8ILKD99e5RAVbDZCC3cyC0l4HLkxc5KcbX+2Kr+8ET8lcP2B04HCEBTVzpgEwxwjGI0JUWyyu2x7yws0cWGvjaoK/nlTtMyeOMVbmDJ/1nbCIddd8uvwGUWuqM9JgyTvFXuv9/nmfxF/NEo38S/DC4rCzd1rmEZHpGzGlrYiqaUEyxYeLdIh3oxUyO01Z1XqhXvN40OhFWU7ReHSgN1XoKi2mr2B4AemJVlrmlUVcMF5OWLd42ScNK60MQXkIAlvnht02/xvbCDrOh0dEuG0pLuxcse/N5UVFR4wYYgpnmo+MNthGM92J5hVA0QkhIGSw="
    - secure: "CVPmA/zaUaL25BRcoFEhkb/hU42GPl3lVaWy/YAwG/tDNGiTt2uvThNw1ayXrRu3HoGvTROLQrw/CdeGCSz8YHuArFDy/Ef3Is71eVn22q6s2GDGZ0yww3SWWfJV3yMIoT5rQlhHrMRD4PCEuwDiDhx1UuDjK/ctaq8/Q3fViv9VEUoxxbEWBl3g/MdVgHZdv4EsciuMcZXiQKcMZ8S1/H5ml1tWKN2IGWHDhGeCuAAOt7t14IDpgsPjDlNRWpzVHso4/tN4WAErZtP8A3y8jyHj9JUhgSDe13KSXRSQSHfhRzSafKQPqno95s1IWUmaIV1mnWQrmEdgi8gIaiaCYK0RfgUjKz9XgctVk2R9ZN4qiUeS36jmVPKDb86Rgl3i6oZdXZuV/rsYSckqwHdiEaI/2xxLCjOyt86JA3LpDSdMdva5W0Jy0I6b+7c42my2EbR++KvFozJPzKZd/7dpYPUzLfZEd6n8+MgB9aZT/wBbf2UkErooFS7Yhn9wzNs6CP/jmhQKT/tbEhmBSk8vxFn7RcMm2MYQApyVjFVu8ze0gpilK4E+ZDbJd20+SYbGq3bpSXald1HeiUjri4HO3AAn/R9RTsGSswEUouLrZ5uGDp1SWtFl1Asf07tScy3JkPISTrYvZnxr4SGygmDQ+xMGPC3DdR/wEFB96pdoTFE="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
